DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    USERNO  NUMBER PRIMARY KEY, -- 회원번호
    USERID   VARCHAR2(15 BYTE) UNIQUE, -- 아이디
    USERPWD   VARCHAR2(15 BYTE) NOT NULL, --비밀번호
    SCHOOLNAME VARCHAR2(30 BYTE) NOT NULL,  -- 학교이름
    AGE   NUMBER, -- 나이
    EMAIL   VARCHAR2(30 BYTE) --이메일
);
DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD(
    POSTNO  NUMBER PRIMARY KEY, -- 게시글 번호
    USERNO  NUMBER, -- 회원번호
    TITLE   VARCHAR2(20 BYTE) NOT NULL,   -- 글 제목
    POST    VARCHAR2(600 BYTE) NOT NULL,   -- 글
    POSTDATE    DATE DEFAULT SYSDATE NOT NULL   -- 게시글 작성일
);

DROP SEQUENCE SEQ_POSTNO;
CREATE SEQUENCE SEQ_POSTNO
NOCACHE;

COMMIT;
